
trigger:
- main

pool: Saliyan

stages:
  - stage: Terraforminit
    jobs:
      - job: terraforminit
        displayName: terraforminit
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
            backendServiceArm: 'slc'
            backendAzureRmStorageAccountName: 'backendstg178'
            backendAzureRmContainerName: 'backendcontainer17'
            backendAzureRmKey: 'dev1.tfstate'

  - stage: Securityscan
    jobs:
      - job: Securityscan
        displayName: Securityscan
        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: |
              tflint --init
              tflint
            workingDirectory: '$(System.DefaultWorkingDirectory)'

  - stage: Terraformplan
    displayName: Plan
    jobs:
      - job: terraformplan
        displayName: Terraform plan
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
            backendServiceArm: 'slc'
            backendAzureRmStorageAccountName: 'backendstg178'
            backendAzureRmContainerName: 'backendcontainer17'
            backendAzureRmKey: 'dev1.tfstate'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
            environmentServiceNameAzureRM: 'slc'

  - stage: Manualvalidation
    displayName: Manualvalidation
    pool: server
    jobs:
      - job: Manualvalidation
        displayName: Manualvalidation
        steps:
        - task: ManualValidation@1
          inputs:
            notifyUsers: 'Saurabh kumar'
            instructions: 'for your approval'