
trigger:
- main

pool: Saliyan

stages:
  - stage: Terraforminit
    jobs:
      - job: terraforminit
        displayName: terraforminit
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
            backendServiceArm: 'slc'
            backendAzureRmStorageAccountName: 'backendstg178'
            backendAzureRmContainerName: 'backendcontainer17'
            backendAzureRmKey: 'dev1.tfstate'

  - stage: Securityscan
    jobs:
      - job: Securityscan
        displayName: Securityscan
        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: |
              tflint --init
              tflint
            workingDirectory: '$(System.DefaultWorkingDirectory)'